extends:
  - eslint:recommended
env:
  node: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
overrides:
  - files:
    - '**/test/*.spec.js'
    env:
      mocha: true
settings:
  polyfills:
    - URL
    - fetch
    - Promise
    - Request

